# Generated by Django 2.0.6 on 2018-10-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('ques', models.TextField()),
                ('ans', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
